import { jsPDF } from "jspdf";
import fs from "fs";

// Helper to add text with word wrapping
const addWrappedText = (doc, text, x, y, maxWidth, lineHeight) => {
    const lines = doc.splitTextToSize(text, maxWidth);
    doc.text(lines, x, y);
    return lines.length * lineHeight;
};

// --- PDF 1: Complete Women's Health Guide ---
const generateGuide = () => {
    const doc = new jsPDF();
    let y = 20;
    const margin = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    const contentWidth = pageWidth - (margin * 2);

    // Title Page
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.setTextColor(233, 30, 99); // Brand Pink
    doc.text("HerHealth: Complete Women's Health Guide", margin, 100);

    doc.setFontSize(14);
    doc.setTextColor(100);
    doc.text("A comprehensive, judgment-free guide to your body.", margin, 115);

    doc.setFontSize(10);
    doc.text("Generated by HerHealth Platform", margin, 280);

    doc.addPage();
    y = 20;

    // Content Structure (Simplified for generation)
    const chapters = [
        { title: "1. Menstrual Cycle", content: "The menstrual cycle is a vital sign of overall health. It consists of four phases: Menstrual, Follicular, Ovulation, and Luteal. Understanding these phases helps you track your health and fertility." },
        { title: "2. Hygiene Practices", content: "Change sanitary products every 4-6 hours. Wash the external genital area with water only. Avoid douching as it disrupts natural pH balance." },
        { title: "3. Spotting & Irregularities", content: "Consult a doctor if you experience heavy bleeding (soaking a pad in an hour), severe pain, or bleeding between periods." },
        { title: "4. PCOD & PCOS", content: "PCOS is a metabolic condition involving insulin resistance and high androgens. Management includes diet, exercise, and sometimes medication." },
        { title: "5. Endometriosis & Fibroids", content: "Endometriosis involves tissue growing outside the uterus causing pain. Fibroids are non-cancerous growths in the uterus. Both can affect fertility." },
        { title: "6. PMS vs PMDD", content: "PMS is common, but PMDD is a severe form causing extreme mood shifts. Treatments include lifestyle changes, therapy, and medication." },
        { title: "7. Sexual Health", content: "Use condoms to prevent STIs. Consent must be enthusiastic and revocable. Regular STI testing is crucial for sexually active individuals." },
        { title: "8. Menopause", content: "Menopause is defined as 12 months without a period. Symptoms include hot flashes and sleep disruption. Hormone therapy can help manage symptoms." },
        { title: "9. Self-care & Lifestyle", content: "Prioritize iron and calcium in your diet. Aim for 150 mins of exercise/week. Sleep and stress management are key to hormonal balance." },
        { title: "10. Red Flags", content: "Seek help for: Sudden severe pelvic pain, lumps in breasts, abnormal discharge with odor, or persistent sadness/anxiety." }
    ];

    chapters.forEach(chapter => {
        if (y > 250) { doc.addPage(); y = 20; }

        doc.setFont("helvetica", "bold");
        doc.setFontSize(16);
        doc.setTextColor(233, 30, 99);
        doc.text(chapter.title, margin, y);
        y += 10;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(12);
        doc.setTextColor(0);
        const linesHeight = addWrappedText(doc, chapter.content, margin, y, contentWidth, 7);
        y += linesHeight + 10;
    });

    // References
    if (y > 250) { doc.addPage(); y = 20; }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("References", margin, y);
    y += 10;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("- World Health Organization (WHO)", margin, y); y += 7;
    doc.text("- American College of Obstetricians and Gynecologists (ACOG)", margin, y); y += 7;
    doc.text("- National Health Service (NHS)", margin, y);

    doc.save("public/complete-guide.pdf");
    console.log("Generated complete-guide.pdf");
};

// --- PDF 2: Symptom Tracker ---
const generateTracker = () => {
    const doc = new jsPDF();
    const margin = 20;

    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(233, 30, 99);
    doc.text("HerHealth Symptom Tracker", margin, 20);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Track your cycle, symptoms, and mood daily.", margin, 28);

    // Table Header
    let y = 40;
    const colWidths = [25, 25, 25, 25, 25, 45];
    const headers = ["Date", "Flow", "Pain", "Mood", "Energy", "Notes"];
    let x = margin;

    doc.setDrawColor(0);
    doc.setFillColor(240, 240, 240);
    doc.rect(margin, y - 6, 170, 8, "F");

    doc.setFont("helvetica", "bold");
    doc.setTextColor(0);
    headers.forEach((header, i) => {
        doc.text(header, x, y);
        x += colWidths[i];
    });

    // Table Rows (Empty for printing)
    y += 10;
    doc.setFont("helvetica", "normal");
    for (let i = 0; i < 15; i++) {
        doc.line(margin, y, margin + 170, y); // Horizontal line
        y += 10;
    }

    // Vertical lines
    x = margin;
    colWidths.forEach(w => {
        doc.line(x, 40 - 6, x, y - 10);
        x += w;
    });
    doc.line(x, 40 - 6, x, y - 10); // Last vertical line

    // Page 2: Red Flags & Checklist
    doc.addPage();
    y = 20;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(233, 30, 99);
    doc.text("Red Flag Symptoms", margin, y);
    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(0);
    const redFlags = [
        "Soaking through one or more pads/tampons every hour.",
        "Bleeding for more than 7 days.",
        "Severe pain that doesn't go away with medication.",
        "Bleeding between periods or after sex.",
        "Post-menopausal bleeding."
    ];
    redFlags.forEach(flag => {
        doc.text(`• ${flag}`, margin, y);
        y += 8;
    });

    y += 10;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(233, 30, 99);
    doc.text("Doctor Visit Checklist", margin, y);
    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(0);
    const checklist = [
        "Date of last period: __________________",
        "Average cycle length: __________________",
        "Current medications: __________________",
        "Family history of: __________________"
    ];
    checklist.forEach(item => {
        doc.text(`[ ] ${item}`, margin, y);
        y += 10;
    });

    doc.save("public/symptom-tracker.pdf");
    console.log("Generated symptom-tracker.pdf");
};

generateGuide();
generateTracker();
